### ISSUE TITLE
Security update for office hours module

### ISSUE THREAD

**Issue by briand44** [ITS-UofIowa/maps.uiowa.edu#2]
Office_hours 7.x-1.4 to 7.x-1.6

**Comment by markahrens** [comment]
This module is going to be removed with the new version of the maps site. Updating this module also broke the current functionality. Due to both of these, I am recommending not updating this.

**Comment by briand44** [comment]
This vulnerability is mitigated by the fact that an attacker must have a role with a permission to add fields to an entity.

**Comment by joewhitsitt** [comment]
This module was removed from the site.
